### ISSUE TITLE
Add a "built with Joy" at the top left of the page

### ISSUE THREAD

**Issue by dokasto** [JoyCreativeCoder/3dconfigurator#1]
<img width="1490" alt="Screenshot 2024-07-12 at 6 41 33 AM" src="https://github.com/user-attachments/assets/3853654b-632e-4571-9fbd-babdcb7601ff">

**Comment by JoyCreativeCoder** [comment]
Will do that now .

**Comment by dokasto** [comment]
![ScreenRecording2024-07-12at3 03 32PM-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/abbb5a13-392b-4c77-ae4e-9044b400fd26)
